"""add table_number to bookings

Revision ID: 4dd716be1c05
Revises: 0596f8a273b2
Create Date: 2025-08-25 15:21:21.431381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd716be1c05'
down_revision: Union[str, Sequence[str], None] = '0596f8a273b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('table_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'table_number')
    # ### end Alembic commands ###
