"""Add ready_at with server_default to preorders

Revision ID: 9434b8974550
Revises: 4dd716be1c05
Create Date: 2025-08-25 16:59:16.293242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9434b8974550'
down_revision: Union[str, Sequence[str], None] = '4dd716be1c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preorders', sa.Column('ready_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preorders', 'ready_at')
    # ### end Alembic commands ###
