"""Add image_id to MenuItem

Revision ID: b1578b7da970
Revises: d2b34350dfda
Create Date: 2025-08-26 12:44:07.263349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1578b7da970'
down_revision: Union[str, Sequence[str], None] = 'd2b34350dfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('image_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'image_id')
    # ### end Alembic commands ###
